name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.2.1

      - name: Install Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm test

      - run: npm run build

  eslint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.2.1

      - name: Install Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run eslint
